[2024-03-01T16:36:03.767+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: datapipeline_Take4.fetch_csvs_from_urls scheduled__2024-03-01T11:02:00+00:00 [queued]>
[2024-03-01T16:36:03.784+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: datapipeline_Take4.fetch_csvs_from_urls scheduled__2024-03-01T11:02:00+00:00 [queued]>
[2024-03-01T16:36:03.784+0530] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-03-01T16:36:03.834+0530] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fetch_csvs_from_urls> on 2024-03-01 11:02:00+00:00
[2024-03-01T16:36:03.842+0530] {standard_task_runner.py:60} INFO - Started process 23027 to run task
[2024-03-01T16:36:03.869+0530] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'datapipeline_Take4', 'fetch_csvs_from_urls', 'scheduled__2024-03-01T11:02:00+00:00', '--job-id', '131', '--raw', '--subdir', 'DAGS_FOLDER/datapipeline_best(2).py', '--cfg-path', '/tmp/tmp6vu8m5r7']
[2024-03-01T16:36:03.879+0530] {standard_task_runner.py:88} INFO - Job 131: Subtask fetch_csvs_from_urls
[2024-03-01T16:36:03.972+0530] {task_command.py:423} INFO - Running <TaskInstance: datapipeline_Take4.fetch_csvs_from_urls scheduled__2024-03-01T11:02:00+00:00 [running]> on host arun-VM
[2024-03-01T16:36:04.282+0530] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='datapipeline_Take4' AIRFLOW_CTX_TASK_ID='fetch_csvs_from_urls' AIRFLOW_CTX_EXECUTION_DATE='2024-03-01T11:02:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-01T11:02:00+00:00'
[2024-03-01T16:36:05.199+0530] {python.py:201} INFO - Done. Returned value was: None
[2024-03-01T16:36:05.215+0530] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=datapipeline_Take4, task_id=fetch_csvs_from_urls, execution_date=20240301T110200, start_date=20240301T110603, end_date=20240301T110605
[2024-03-01T16:36:05.458+0530] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-01T16:36:05.525+0530] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
