[2024-02-29T18:13:54.203+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: THE_second_dag.first_task scheduled__2024-02-27T00:00:00+00:00 [queued]>
[2024-02-29T18:13:54.211+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: THE_second_dag.first_task scheduled__2024-02-27T00:00:00+00:00 [queued]>
[2024-02-29T18:13:54.211+0530] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-02-29T18:13:54.292+0530] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): first_task> on 2024-02-27 00:00:00+00:00
[2024-02-29T18:13:54.302+0530] {standard_task_runner.py:60} INFO - Started process 5053 to run task
[2024-02-29T18:13:54.318+0530] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'THE_second_dag', 'first_task', 'scheduled__2024-02-27T00:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/.ipynb_checkpoints/first-dag-1-checkpoint.py', '--cfg-path', '/tmp/tmp67w64el7']
[2024-02-29T18:13:54.319+0530] {standard_task_runner.py:88} INFO - Job 30: Subtask first_task
[2024-02-29T18:13:54.470+0530] {task_command.py:423} INFO - Running <TaskInstance: THE_second_dag.first_task scheduled__2024-02-27T00:00:00+00:00 [running]> on host arun-VM
[2024-02-29T18:13:54.680+0530] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='THE_second_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-27T00:00:00+00:00'
[2024-02-29T18:13:54.686+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-02-29T18:13:54.687+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello world, this is the first task!']
[2024-02-29T18:13:54.707+0530] {subprocess.py:86} INFO - Output:
[2024-02-29T18:13:54.710+0530] {subprocess.py:93} INFO - hello world, this is the first task!
[2024-02-29T18:13:54.710+0530] {subprocess.py:97} INFO - Command exited with return code 0
[2024-02-29T18:13:54.742+0530] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=THE_second_dag, task_id=first_task, execution_date=20240227T000000, start_date=20240229T124354, end_date=20240229T124354
[2024-02-29T18:13:54.783+0530] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-29T18:13:54.799+0530] {taskinstance.py:3280} INFO - 2 downstream tasks scheduled from follow-on schedule check
