[2024-02-29T18:19:43.747+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: THE_second_dag.second_task scheduled__2024-02-29T00:02:00+00:00 [queued]>
[2024-02-29T18:19:43.756+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: THE_second_dag.second_task scheduled__2024-02-29T00:02:00+00:00 [queued]>
[2024-02-29T18:19:43.756+0530] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-02-29T18:19:43.824+0530] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): second_task> on 2024-02-29 00:02:00+00:00
[2024-02-29T18:19:43.828+0530] {standard_task_runner.py:60} INFO - Started process 5440 to run task
[2024-02-29T18:19:43.832+0530] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'THE_second_dag', 'second_task', 'scheduled__2024-02-29T00:02:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/.ipynb_checkpoints/first-dag-1-checkpoint.py', '--cfg-path', '/tmp/tmpzgd0f96s']
[2024-02-29T18:19:43.832+0530] {standard_task_runner.py:88} INFO - Job 43: Subtask second_task
[2024-02-29T18:19:44.080+0530] {task_command.py:423} INFO - Running <TaskInstance: THE_second_dag.second_task scheduled__2024-02-29T00:02:00+00:00 [running]> on host arun-VM
[2024-02-29T18:19:44.365+0530] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='THE_second_dag' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-29T00:02:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-29T00:02:00+00:00'
[2024-02-29T18:19:44.373+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-02-29T18:19:44.376+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, I am task2 and will be running after task1!']
[2024-02-29T18:19:44.409+0530] {subprocess.py:86} INFO - Output:
[2024-02-29T18:19:44.427+0530] {subprocess.py:93} INFO - hey, I am task2 and will be running after task1!
[2024-02-29T18:19:44.428+0530] {subprocess.py:97} INFO - Command exited with return code 0
[2024-02-29T18:19:44.485+0530] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=THE_second_dag, task_id=second_task, execution_date=20240229T000200, start_date=20240229T124943, end_date=20240229T124944
[2024-02-29T18:19:44.576+0530] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-29T18:19:44.589+0530] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
