[2024-02-23T14:44:42.863+0530] {processor.py:161} INFO - Started process (PID=4724) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:44:42.867+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T14:44:42.871+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:44:42.869+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:44:42.885+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:44:42.883+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T14:44:42.886+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:44:42.886+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T14:44:42.887+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:44:42.931+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.082 seconds
[2024-02-23T14:45:48.887+0530] {processor.py:161} INFO - Started process (PID=4821) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:45:48.894+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T14:45:48.899+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:45:48.897+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:45:48.914+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:45:48.911+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T14:45:48.915+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:45:48.914+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T14:45:48.916+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:45:48.948+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.075 seconds
[2024-02-23T14:48:00.090+0530] {processor.py:161} INFO - Started process (PID=5206) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:48:00.094+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T14:48:00.097+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:48:00.095+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:48:00.104+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:48:00.103+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T14:48:00.105+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:48:00.104+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T14:48:00.105+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:48:00.128+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2024-02-23T14:49:12.936+0530] {processor.py:161} INFO - Started process (PID=5313) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:49:12.940+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T14:49:12.941+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:49:12.941+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:49:12.946+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:49:12.945+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T14:49:12.946+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:49:12.946+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T14:49:12.947+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:49:12.961+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2024-02-23T14:50:13.247+0530] {processor.py:161} INFO - Started process (PID=5373) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:50:13.279+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T14:50:13.285+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:50:13.285+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:50:13.290+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:50:13.289+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T14:50:13.291+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:50:13.290+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T14:50:13.291+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:50:13.322+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.088 seconds
[2024-02-23T14:51:12.513+0530] {processor.py:161} INFO - Started process (PID=5422) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:51:12.520+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T14:51:12.526+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:51:12.523+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:51:12.544+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:51:12.541+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T14:51:12.545+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:51:12.545+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T14:51:12.547+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:51:12.576+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.084 seconds
[2024-02-23T14:52:10.492+0530] {processor.py:161} INFO - Started process (PID=5472) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:52:10.512+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T14:52:10.515+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:52:10.515+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:52:10.525+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:52:10.523+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T14:52:10.526+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:52:10.526+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T14:52:10.526+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:52:10.542+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.056 seconds
[2024-02-23T14:53:09.651+0530] {processor.py:161} INFO - Started process (PID=5521) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:53:09.653+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T14:53:09.654+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:53:09.653+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:53:09.659+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:53:09.658+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T14:53:09.659+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:53:09.659+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T14:53:09.660+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:53:09.674+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2024-02-23T14:54:02.208+0530] {processor.py:161} INFO - Started process (PID=5578) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:54:02.247+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T14:54:02.252+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:54:02.250+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:54:02.266+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:54:02.265+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T14:54:02.271+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:54:02.267+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T14:54:02.271+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:54:02.316+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.113 seconds
[2024-02-23T14:55:04.860+0530] {processor.py:161} INFO - Started process (PID=5952) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:55:04.862+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T14:55:04.863+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:55:04.862+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:55:04.868+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:55:04.867+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T14:55:04.868+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:55:04.868+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T14:55:04.869+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:55:04.883+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2024-02-23T14:56:03.358+0530] {processor.py:161} INFO - Started process (PID=6074) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:56:03.381+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T14:56:03.386+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:56:03.385+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:56:03.391+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:56:03.390+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T14:56:03.392+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:56:03.392+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T14:56:03.392+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:56:03.424+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.078 seconds
[2024-02-23T14:56:56.698+0530] {processor.py:161} INFO - Started process (PID=6158) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:56:56.711+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T14:56:56.714+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:56:56.713+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:56:56.722+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:56:56.721+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T14:56:56.723+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:56:56.723+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T14:56:56.724+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:56:56.756+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.065 seconds
[2024-02-23T14:57:54.312+0530] {processor.py:161} INFO - Started process (PID=6254) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:57:54.354+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T14:57:54.358+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:57:54.356+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:57:54.373+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:57:54.371+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T14:57:54.374+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:57:54.374+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T14:57:54.375+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:57:54.428+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.130 seconds
[2024-02-23T14:58:47.777+0530] {processor.py:161} INFO - Started process (PID=6332) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:58:47.812+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T14:58:47.813+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:58:47.813+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:58:47.819+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:58:47.818+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T14:58:47.820+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:58:47.820+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T14:58:47.821+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:58:47.835+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.074 seconds
[2024-02-23T14:59:40.412+0530] {processor.py:161} INFO - Started process (PID=6426) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:59:40.415+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T14:59:40.416+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:59:40.416+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:59:40.421+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:59:40.421+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T14:59:40.422+0530] {logging_mixin.py:188} INFO - [2024-02-23T14:59:40.422+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T14:59:40.422+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T14:59:40.438+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2024-02-23T15:00:47.177+0530] {processor.py:161} INFO - Started process (PID=6516) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:00:47.217+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:00:47.222+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:00:47.220+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:00:47.231+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:00:47.230+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:00:47.231+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:00:47.231+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:00:47.232+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:00:47.260+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.091 seconds
[2024-02-23T15:01:51.312+0530] {processor.py:161} INFO - Started process (PID=6617) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:01:51.358+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:01:51.363+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:01:51.361+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:01:51.382+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:01:51.380+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:01:51.383+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:01:51.382+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:01:51.384+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:01:51.427+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.127 seconds
[2024-02-23T15:03:00.562+0530] {processor.py:161} INFO - Started process (PID=6829) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:03:00.603+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:03:00.614+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:03:00.604+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:03:00.623+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:03:00.622+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:03:00.623+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:03:00.623+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:03:00.623+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:03:00.645+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.094 seconds
[2024-02-23T15:04:09.765+0530] {processor.py:161} INFO - Started process (PID=6983) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:04:09.812+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:04:09.823+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:04:09.820+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:04:09.840+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:04:09.839+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:04:09.840+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:04:09.840+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:04:09.840+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:04:09.863+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.103 seconds
[2024-02-23T15:05:10.259+0530] {processor.py:161} INFO - Started process (PID=7161) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:05:10.276+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:05:10.282+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:05:10.276+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:05:10.295+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:05:10.291+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:05:10.296+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:05:10.296+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:05:10.296+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:05:10.312+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.063 seconds
[2024-02-23T15:06:13.449+0530] {processor.py:161} INFO - Started process (PID=7303) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:06:13.480+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:06:13.482+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:06:13.481+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:06:13.488+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:06:13.487+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:06:13.488+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:06:13.488+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:06:13.489+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:06:13.505+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2024-02-23T15:07:11.875+0530] {processor.py:161} INFO - Started process (PID=7369) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:07:11.896+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:07:11.898+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:07:11.898+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:07:11.904+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:07:11.903+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:07:11.905+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:07:11.904+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:07:11.905+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:07:11.921+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2024-02-23T15:08:05.505+0530] {processor.py:161} INFO - Started process (PID=7419) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:08:05.507+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:08:05.511+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:08:05.510+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:08:05.517+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:08:05.517+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:08:05.518+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:08:05.518+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:08:05.518+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:08:05.533+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2024-02-23T15:08:59.946+0530] {processor.py:161} INFO - Started process (PID=7471) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:08:59.953+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:08:59.956+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:08:59.955+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:08:59.976+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:08:59.972+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:08:59.977+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:08:59.977+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:08:59.978+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:09:00.017+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.088 seconds
[2024-02-23T15:09:53.942+0530] {processor.py:161} INFO - Started process (PID=7567) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:09:53.944+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:09:53.945+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:09:53.945+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:09:53.951+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:09:53.950+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:09:53.951+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:09:53.951+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:09:53.951+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:09:53.967+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2024-02-23T15:10:55.190+0530] {processor.py:161} INFO - Started process (PID=7645) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:10:55.247+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:10:55.254+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:10:55.251+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:10:55.273+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:10:55.271+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:10:55.274+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:10:55.274+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:10:55.275+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:10:55.330+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.152 seconds
[2024-02-23T15:11:53.590+0530] {processor.py:161} INFO - Started process (PID=7736) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:11:53.599+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:11:53.601+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:11:53.601+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:11:53.617+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:11:53.608+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:11:53.618+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:11:53.617+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:11:53.623+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:11:53.663+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.084 seconds
[2024-02-23T15:12:50.922+0530] {processor.py:161} INFO - Started process (PID=7868) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:12:50.931+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:12:50.933+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:12:50.932+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:12:50.989+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:12:50.988+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:12:50.989+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:12:50.989+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:12:50.990+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:12:51.012+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.099 seconds
[2024-02-23T15:13:45.532+0530] {processor.py:161} INFO - Started process (PID=7925) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:13:45.536+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:13:45.539+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:13:45.538+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:13:45.545+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:13:45.544+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:13:45.546+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:13:45.545+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:13:45.546+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:13:45.563+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2024-02-23T15:14:39.670+0530] {processor.py:161} INFO - Started process (PID=7975) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:14:39.674+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:14:39.675+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:14:39.675+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:14:39.681+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:14:39.680+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:14:39.681+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:14:39.681+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:14:39.682+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:14:39.697+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2024-02-23T15:15:32.106+0530] {processor.py:161} INFO - Started process (PID=8028) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:15:32.110+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:15:32.113+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:15:32.112+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:15:32.123+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:15:32.122+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:15:32.125+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:15:32.124+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:15:32.125+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:15:32.158+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.061 seconds
[2024-02-23T15:16:25.727+0530] {processor.py:161} INFO - Started process (PID=8087) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:16:25.738+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:16:25.745+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:16:25.742+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:16:25.765+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:16:25.762+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:16:25.767+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:16:25.766+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:16:25.768+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:16:25.812+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.098 seconds
[2024-02-23T15:17:26.415+0530] {processor.py:161} INFO - Started process (PID=8218) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:17:26.421+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:17:26.426+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:17:26.423+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:17:26.442+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:17:26.440+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:17:26.443+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:17:26.443+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:17:26.445+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:17:26.492+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.093 seconds
[2024-02-23T15:18:22.842+0530] {processor.py:161} INFO - Started process (PID=8281) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:18:22.853+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:18:22.858+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:18:22.856+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:18:22.873+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:18:22.871+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:18:22.874+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:18:22.874+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:18:22.875+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:18:22.916+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.085 seconds
[2024-02-23T15:19:24.756+0530] {processor.py:161} INFO - Started process (PID=8413) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:19:24.782+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:19:24.788+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:19:24.783+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:19:24.807+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:19:24.803+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:19:24.812+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:19:24.808+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:19:24.820+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:19:24.850+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.102 seconds
[2024-02-23T15:20:51.695+0530] {processor.py:161} INFO - Started process (PID=8520) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:20:51.748+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:20:51.776+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:20:51.775+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:20:51.788+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:20:51.787+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:20:51.789+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:20:51.789+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:20:51.790+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:20:51.855+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.174 seconds
[2024-02-23T15:21:55.462+0530] {processor.py:161} INFO - Started process (PID=8612) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:21:55.474+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:21:55.479+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:21:55.478+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:21:55.489+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:21:55.489+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:21:55.490+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:21:55.490+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:21:55.490+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:21:55.508+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.051 seconds
[2024-02-23T15:22:53.089+0530] {processor.py:161} INFO - Started process (PID=8711) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:22:53.131+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:22:53.133+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:22:53.132+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:22:53.138+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:22:53.137+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:22:53.138+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:22:53.138+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:22:53.139+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:22:53.174+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.088 seconds
[2024-02-23T15:23:53.331+0530] {processor.py:161} INFO - Started process (PID=8803) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:23:53.373+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:23:53.375+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:23:53.374+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:23:53.406+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:23:53.405+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:23:53.406+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:23:53.406+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:23:53.407+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:23:53.444+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.117 seconds
[2024-02-23T15:24:49.312+0530] {processor.py:161} INFO - Started process (PID=8929) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:24:49.314+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:24:49.315+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:24:49.314+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:24:49.320+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:24:49.319+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:24:49.320+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:24:49.320+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:24:49.320+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:24:49.333+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-02-23T15:25:41.085+0530] {processor.py:161} INFO - Started process (PID=9138) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:25:41.089+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:25:41.090+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:25:41.089+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:25:41.093+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:25:41.093+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:25:41.093+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:25:41.093+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:25:41.094+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:25:41.102+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-02-23T15:26:33.052+0530] {processor.py:161} INFO - Started process (PID=9241) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:26:33.089+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:26:33.090+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:26:33.090+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:26:33.094+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:26:33.093+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:26:33.094+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:26:33.094+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:26:33.094+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:26:33.104+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.056 seconds
[2024-02-23T15:27:40.588+0530] {processor.py:161} INFO - Started process (PID=9350) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:27:40.662+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:27:40.664+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:27:40.663+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:27:40.703+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:27:40.699+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:27:40.703+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:27:40.703+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:27:40.704+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:27:40.745+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.167 seconds
[2024-02-23T15:28:34.658+0530] {processor.py:161} INFO - Started process (PID=9437) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:28:34.698+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:28:34.700+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:28:34.699+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:28:34.706+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:28:34.706+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:28:34.707+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:28:34.707+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:28:34.707+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:28:34.722+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.071 seconds
[2024-02-23T15:29:23.292+0530] {processor.py:161} INFO - Started process (PID=9490) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:29:23.333+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:29:23.335+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:29:23.335+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:29:23.338+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:29:23.338+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:29:23.339+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:29:23.339+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:29:23.339+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:29:23.348+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.060 seconds
[2024-02-23T15:30:40.263+0530] {processor.py:161} INFO - Started process (PID=9630) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:30:40.271+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:30:40.272+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:30:40.272+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:30:40.276+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:30:40.276+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:30:40.276+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:30:40.276+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:30:40.276+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:30:40.286+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2024-02-23T15:31:38.743+0530] {processor.py:161} INFO - Started process (PID=9835) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:31:38.822+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:31:38.828+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:31:38.827+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:31:38.851+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:31:38.849+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:31:38.852+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:31:38.852+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:31:38.853+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:31:38.896+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.161 seconds
[2024-02-23T15:32:46.066+0530] {processor.py:161} INFO - Started process (PID=10111) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:32:46.110+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:32:46.112+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:32:46.111+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:32:46.120+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:32:46.118+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:32:46.121+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:32:46.121+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:32:46.121+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:32:46.144+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.082 seconds
[2024-02-23T15:33:42.114+0530] {processor.py:161} INFO - Started process (PID=10197) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:33:42.202+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:33:42.204+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:33:42.203+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:33:42.212+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:33:42.211+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:33:42.213+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:33:42.213+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:33:42.213+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:33:42.233+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.124 seconds
[2024-02-23T15:34:46.046+0530] {processor.py:161} INFO - Started process (PID=10344) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:34:46.048+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:34:46.050+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:34:46.049+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:34:46.056+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:34:46.055+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:34:46.056+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:34:46.056+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:34:46.057+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:34:46.077+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.059 seconds
[2024-02-23T15:35:43.417+0530] {processor.py:161} INFO - Started process (PID=10439) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:35:43.429+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:35:43.431+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:35:43.430+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:35:43.438+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:35:43.438+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:35:43.439+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:35:43.439+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:35:43.440+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:35:43.461+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2024-02-23T15:36:39.015+0530] {processor.py:161} INFO - Started process (PID=10600) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:36:39.016+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:36:39.017+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:36:39.017+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:36:39.025+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:36:39.025+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:36:39.026+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:36:39.026+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:36:39.026+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:36:39.039+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2024-02-23T15:37:33.102+0530] {processor.py:161} INFO - Started process (PID=10697) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:37:33.103+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:37:33.104+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:37:33.104+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:37:33.109+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:37:33.108+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:37:33.109+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:37:33.109+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:37:33.109+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:37:33.119+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2024-02-23T15:38:44.569+0530] {processor.py:161} INFO - Started process (PID=10821) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:38:44.609+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:38:44.611+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:38:44.610+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:38:44.624+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:38:44.620+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:38:44.628+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:38:44.624+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:38:44.628+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:38:44.685+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.128 seconds
[2024-02-23T15:39:38.250+0530] {processor.py:161} INFO - Started process (PID=10902) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:39:38.274+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:39:38.276+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:39:38.275+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:39:38.280+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:39:38.279+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:39:38.281+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:39:38.281+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:39:38.281+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:39:38.295+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.049 seconds
[2024-02-23T15:40:37.379+0530] {processor.py:161} INFO - Started process (PID=11010) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:40:37.395+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:40:37.397+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:40:37.396+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:40:37.405+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:40:37.404+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:40:37.406+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:40:37.405+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:40:37.406+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:40:37.441+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
[2024-02-23T15:41:36.067+0530] {processor.py:161} INFO - Started process (PID=11088) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:41:36.103+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:41:36.105+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:41:36.104+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:41:36.110+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:41:36.109+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:41:36.111+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:41:36.111+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:41:36.112+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:41:36.127+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2024-02-23T15:42:29.273+0530] {processor.py:161} INFO - Started process (PID=11149) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:42:29.309+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:42:29.310+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:42:29.309+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:42:29.315+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:42:29.315+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:42:29.316+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:42:29.315+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:42:29.316+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:42:29.331+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.062 seconds
[2024-02-23T15:43:18.712+0530] {processor.py:161} INFO - Started process (PID=11200) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:43:18.714+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:43:18.715+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:43:18.714+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:43:18.719+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:43:18.718+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:43:18.719+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:43:18.719+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:43:18.720+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:43:18.732+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-02-23T15:44:34.988+0530] {processor.py:161} INFO - Started process (PID=11296) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:44:34.991+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:44:34.993+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:44:34.992+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:44:35.000+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:44:34.999+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:44:35.001+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:44:35.000+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:44:35.001+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:44:35.042+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.065 seconds
[2024-02-23T15:45:32.389+0530] {processor.py:161} INFO - Started process (PID=11396) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:45:32.424+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:45:32.425+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:45:32.424+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:45:32.428+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:45:32.428+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:45:32.429+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:45:32.429+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:45:32.429+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:45:32.439+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.054 seconds
[2024-02-23T15:46:23.966+0530] {processor.py:161} INFO - Started process (PID=11488) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:46:23.997+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:46:24.000+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:46:23.999+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:46:24.006+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:46:24.006+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:46:24.007+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:46:24.007+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:46:24.008+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:46:24.035+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.088 seconds
[2024-02-23T15:47:18.219+0530] {processor.py:161} INFO - Started process (PID=11563) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:47:18.221+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:47:18.222+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:47:18.221+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:47:18.226+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:47:18.225+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:47:18.226+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:47:18.226+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:47:18.226+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:47:18.237+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-02-23T15:48:30.467+0530] {processor.py:161} INFO - Started process (PID=11685) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:48:30.498+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:48:30.499+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:48:30.498+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:48:30.502+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:48:30.502+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:48:30.503+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:48:30.502+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:48:30.503+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:48:30.513+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.049 seconds
[2024-02-23T15:49:21.369+0530] {processor.py:161} INFO - Started process (PID=11764) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:49:21.386+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:49:21.387+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:49:21.387+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:49:21.391+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:49:21.390+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:49:21.391+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:49:21.391+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:49:21.391+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:49:21.403+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2024-02-23T15:50:38.558+0530] {processor.py:161} INFO - Started process (PID=11898) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:50:38.561+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:50:38.565+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:50:38.564+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:50:38.574+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:50:38.573+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:50:38.574+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:50:38.574+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:50:38.575+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:50:38.610+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.065 seconds
[2024-02-23T15:51:39.373+0530] {processor.py:161} INFO - Started process (PID=11998) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:51:39.375+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:51:39.378+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:51:39.377+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:51:39.385+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:51:39.384+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:51:39.385+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:51:39.385+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:51:39.386+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:51:39.405+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2024-02-23T15:52:32.254+0530] {processor.py:161} INFO - Started process (PID=12079) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:52:32.290+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:52:32.291+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:52:32.291+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:52:32.295+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:52:32.295+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:52:32.296+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:52:32.295+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:52:32.297+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:52:32.313+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.062 seconds
[2024-02-23T15:53:24.028+0530] {processor.py:161} INFO - Started process (PID=12160) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:53:24.034+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:53:24.035+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:53:24.035+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:53:24.041+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:53:24.040+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:53:24.041+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:53:24.041+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:53:24.042+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:53:24.104+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.080 seconds
[2024-02-23T15:54:16.025+0530] {processor.py:161} INFO - Started process (PID=12236) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:54:16.062+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:54:16.064+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:54:16.063+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:54:16.068+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:54:16.068+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:54:16.069+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:54:16.068+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:54:16.069+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:54:16.080+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.061 seconds
[2024-02-23T15:55:08.268+0530] {processor.py:161} INFO - Started process (PID=12303) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:55:08.270+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:55:08.271+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:55:08.270+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:55:08.274+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:55:08.274+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:55:08.274+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:55:08.274+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:55:08.275+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:55:08.285+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2024-02-23T15:55:59.035+0530] {processor.py:161} INFO - Started process (PID=12353) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:55:59.077+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:55:59.078+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:55:59.078+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:55:59.083+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:55:59.082+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:55:59.083+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:55:59.083+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:55:59.083+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:55:59.095+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2024-02-23T15:57:03.060+0530] {processor.py:161} INFO - Started process (PID=12417) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:57:03.062+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:57:03.063+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:57:03.062+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:57:03.066+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:57:03.066+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:57:03.066+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:57:03.066+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:57:03.067+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:57:03.086+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2024-02-23T15:58:04.530+0530] {processor.py:161} INFO - Started process (PID=12484) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:58:04.531+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:58:04.532+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:58:04.532+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:58:04.537+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:58:04.536+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:58:04.537+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:58:04.537+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:58:04.537+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:58:04.550+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-02-23T15:59:08.569+0530] {processor.py:161} INFO - Started process (PID=12551) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:59:08.601+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T15:59:08.602+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:59:08.602+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:59:08.606+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:59:08.605+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T15:59:08.606+0530] {logging_mixin.py:188} INFO - [2024-02-23T15:59:08.606+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T15:59:08.606+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T15:59:08.617+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.051 seconds
[2024-02-23T16:00:11.228+0530] {processor.py:161} INFO - Started process (PID=12749) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:00:11.265+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T16:00:11.266+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:00:11.266+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:00:11.269+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:00:11.269+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T16:00:11.270+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:00:11.270+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T16:00:11.270+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:00:11.279+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.054 seconds
[2024-02-23T16:01:09.673+0530] {processor.py:161} INFO - Started process (PID=12813) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:01:09.710+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T16:01:09.711+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:01:09.710+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:01:09.715+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:01:09.714+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T16:01:09.716+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:01:09.716+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T16:01:09.716+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:01:09.727+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2024-02-23T16:02:09.313+0530] {processor.py:161} INFO - Started process (PID=12873) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:02:09.349+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T16:02:09.352+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:02:09.351+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:02:09.361+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:02:09.360+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T16:02:09.362+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:02:09.361+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T16:02:09.362+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:02:09.376+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.066 seconds
[2024-02-23T16:03:14.416+0530] {processor.py:161} INFO - Started process (PID=12940) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:03:14.418+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T16:03:14.420+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:03:14.419+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:03:14.427+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:03:14.426+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T16:03:14.428+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:03:14.427+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T16:03:14.429+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:03:14.448+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2024-02-23T16:04:03.022+0530] {processor.py:161} INFO - Started process (PID=12985) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:04:03.057+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T16:04:03.059+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:04:03.058+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:04:03.064+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:04:03.063+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T16:04:03.065+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:04:03.065+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T16:04:03.065+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:04:03.082+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.065 seconds
[2024-02-23T16:04:52.232+0530] {processor.py:161} INFO - Started process (PID=13036) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:04:52.274+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T16:04:52.280+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:04:52.278+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:04:52.301+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:04:52.299+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T16:04:52.305+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:04:52.302+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T16:04:52.306+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:04:52.351+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.128 seconds
[2024-02-23T16:05:47.594+0530] {processor.py:161} INFO - Started process (PID=13089) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:05:47.606+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T16:05:47.608+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:05:47.607+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:05:47.614+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:05:47.613+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T16:05:47.615+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:05:47.614+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T16:05:47.615+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:05:47.629+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2024-02-23T16:06:42.739+0530] {processor.py:161} INFO - Started process (PID=13140) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:06:42.750+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T16:06:42.763+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:06:42.753+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:06:42.791+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:06:42.791+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T16:06:42.792+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:06:42.792+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T16:06:42.793+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:06:42.808+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.081 seconds
[2024-02-23T16:07:36.679+0530] {processor.py:161} INFO - Started process (PID=13189) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:07:36.717+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T16:07:36.719+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:07:36.718+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:07:36.725+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:07:36.724+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T16:07:36.726+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:07:36.725+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T16:07:36.726+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:07:36.744+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2024-02-23T16:08:35.632+0530] {processor.py:161} INFO - Started process (PID=13243) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:08:35.673+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T16:08:35.674+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:08:35.674+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:08:35.680+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:08:35.679+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T16:08:35.681+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:08:35.681+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T16:08:35.681+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:08:35.696+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2024-02-23T16:09:35.688+0530] {processor.py:161} INFO - Started process (PID=13293) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:09:35.691+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T16:09:35.693+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:09:35.692+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:09:35.698+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:09:35.697+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T16:09:35.699+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:09:35.698+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T16:09:35.699+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:09:35.714+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2024-02-23T16:10:28.887+0530] {processor.py:161} INFO - Started process (PID=13348) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:10:28.901+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T16:10:28.902+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:10:28.902+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:10:28.906+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:10:28.906+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T16:10:28.906+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:10:28.906+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T16:10:28.907+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:10:28.918+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2024-02-23T16:11:35.932+0530] {processor.py:161} INFO - Started process (PID=13417) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:11:35.968+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T16:11:35.969+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:11:35.969+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:11:35.973+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:11:35.973+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T16:11:35.974+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:11:35.973+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T16:11:35.974+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:11:35.985+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.057 seconds
[2024-02-23T16:12:33.634+0530] {processor.py:161} INFO - Started process (PID=13478) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:12:33.668+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T16:12:33.669+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:12:33.669+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:12:33.675+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:12:33.674+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T16:12:33.675+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:12:33.675+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T16:12:33.675+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:12:33.692+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.062 seconds
[2024-02-23T16:13:40.780+0530] {processor.py:161} INFO - Started process (PID=13545) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:13:40.782+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T16:13:40.784+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:13:40.783+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:13:40.792+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:13:40.791+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T16:13:40.793+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:13:40.792+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T16:13:40.793+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:13:40.812+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2024-02-23T16:14:31.560+0530] {processor.py:161} INFO - Started process (PID=13593) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:14:31.562+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T16:14:31.563+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:14:31.563+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:14:31.568+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:14:31.567+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T16:14:31.568+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:14:31.568+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T16:14:31.568+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:14:31.581+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-02-23T16:15:28.163+0530] {processor.py:161} INFO - Started process (PID=13780) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:15:28.173+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T16:15:28.175+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:15:28.174+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:15:28.182+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:15:28.182+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T16:15:28.183+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:15:28.183+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T16:15:28.183+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:15:28.209+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2024-02-23T16:16:18.866+0530] {processor.py:161} INFO - Started process (PID=13833) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:16:18.872+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T16:16:18.873+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:16:18.873+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:16:18.877+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:16:18.877+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T16:16:18.877+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:16:18.877+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T16:16:18.878+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:16:18.889+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-02-23T16:17:19.473+0530] {processor.py:161} INFO - Started process (PID=13901) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:17:19.504+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T16:17:19.505+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:17:19.505+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:17:19.510+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:17:19.509+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T16:17:19.510+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:17:19.510+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T16:17:19.510+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:17:19.522+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.055 seconds
[2024-02-23T16:18:26.526+0530] {processor.py:161} INFO - Started process (PID=13984) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:18:26.563+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T16:18:26.564+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:18:26.564+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:18:26.575+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:18:26.574+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T16:18:26.576+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:18:26.576+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T16:18:26.576+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:18:26.593+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.081 seconds
[2024-02-23T16:19:16.324+0530] {processor.py:161} INFO - Started process (PID=14042) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:19:16.372+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T16:19:16.375+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:19:16.374+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:19:16.395+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:19:16.394+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T16:19:16.395+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:19:16.395+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T16:19:16.399+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:19:16.444+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.137 seconds
[2024-02-23T16:20:29.502+0530] {processor.py:161} INFO - Started process (PID=14147) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:20:29.504+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T16:20:29.505+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:20:29.505+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:20:29.512+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:20:29.510+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T16:20:29.512+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:20:29.512+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T16:20:29.512+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:20:29.530+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2024-02-23T16:21:18.971+0530] {processor.py:161} INFO - Started process (PID=14212) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:21:18.973+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T16:21:18.974+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:21:18.973+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:21:18.979+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:21:18.978+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T16:21:18.979+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:21:18.979+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T16:21:18.979+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:21:19.042+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.076 seconds
[2024-02-23T16:22:25.771+0530] {processor.py:161} INFO - Started process (PID=14322) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:22:25.791+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T16:22:25.793+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:22:25.793+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:22:25.800+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:22:25.798+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T16:22:25.800+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:22:25.800+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T16:22:25.801+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:22:25.872+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.117 seconds
[2024-02-23T16:23:19.662+0530] {processor.py:161} INFO - Started process (PID=14424) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:23:19.664+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T16:23:19.665+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:23:19.664+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:23:19.669+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:23:19.669+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T16:23:19.670+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:23:19.670+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T16:23:19.670+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:23:19.682+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-02-23T16:24:12.293+0530] {processor.py:161} INFO - Started process (PID=14510) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:24:12.361+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T16:24:12.362+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:24:12.362+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:24:12.367+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:24:12.366+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T16:24:12.367+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:24:12.367+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T16:24:12.367+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:24:12.379+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.090 seconds
[2024-02-23T16:25:22.804+0530] {processor.py:161} INFO - Started process (PID=14622) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:25:22.847+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T16:25:22.849+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:25:22.848+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:25:22.855+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:25:22.854+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T16:25:22.856+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:25:22.855+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T16:25:22.856+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:25:22.872+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.073 seconds
[2024-02-23T16:26:12.156+0530] {processor.py:161} INFO - Started process (PID=14742) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:26:12.194+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T16:26:12.195+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:26:12.195+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:26:12.202+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:26:12.201+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T16:26:12.202+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:26:12.202+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T16:26:12.202+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:26:12.216+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.065 seconds
[2024-02-23T16:27:04.816+0530] {processor.py:161} INFO - Started process (PID=14874) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:27:04.852+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T16:27:04.853+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:27:04.853+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:27:04.857+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:27:04.856+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T16:27:04.857+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:27:04.857+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T16:27:04.858+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:27:04.869+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.056 seconds
[2024-02-23T16:27:51.591+0530] {processor.py:161} INFO - Started process (PID=14935) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:27:51.637+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T16:27:51.639+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:27:51.638+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:27:51.646+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:27:51.645+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T16:27:51.647+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:27:51.646+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T16:27:51.647+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:27:51.707+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.122 seconds
[2024-02-23T16:28:52.588+0530] {processor.py:161} INFO - Started process (PID=15034) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:28:52.628+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T16:28:52.629+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:28:52.628+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:28:52.632+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:28:52.632+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T16:28:52.632+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:28:52.632+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T16:28:52.633+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:28:52.643+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2024-02-23T16:29:58.650+0530] {processor.py:161} INFO - Started process (PID=15140) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:29:58.652+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T16:29:58.654+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:29:58.653+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:29:58.659+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:29:58.658+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T16:29:58.659+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:29:58.659+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T16:29:58.660+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:29:58.685+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.051 seconds
[2024-02-23T16:31:06.372+0530] {processor.py:161} INFO - Started process (PID=15231) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:31:06.390+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T16:31:06.392+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:31:06.392+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:31:06.398+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:31:06.397+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T16:31:06.398+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:31:06.398+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T16:31:06.399+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:31:06.429+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.062 seconds
[2024-02-23T16:31:57.099+0530] {processor.py:161} INFO - Started process (PID=15298) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:31:57.131+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T16:31:57.133+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:31:57.132+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:31:57.137+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:31:57.136+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T16:31:57.137+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:31:57.137+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T16:31:57.138+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:31:57.150+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.055 seconds
[2024-02-23T16:32:46.102+0530] {processor.py:161} INFO - Started process (PID=15372) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:32:46.113+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T16:32:46.117+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:32:46.115+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:32:46.134+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:32:46.130+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T16:32:46.134+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:32:46.134+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T16:32:46.135+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:32:46.207+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.114 seconds
[2024-02-23T16:33:35.936+0530] {processor.py:161} INFO - Started process (PID=15448) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:33:35.948+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T16:33:35.954+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:33:35.949+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:33:35.959+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:33:35.958+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T16:33:35.959+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:33:35.959+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T16:33:35.972+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:33:35.990+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.059 seconds
[2024-02-23T16:34:26.690+0530] {processor.py:161} INFO - Started process (PID=15538) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:34:26.693+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T16:34:26.694+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:34:26.694+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:34:26.701+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:34:26.700+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T16:34:26.701+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:34:26.701+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T16:34:26.702+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:34:26.721+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2024-02-23T16:35:38.065+0530] {processor.py:161} INFO - Started process (PID=15647) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:35:38.115+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T16:35:38.117+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:35:38.117+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:35:38.124+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:35:38.124+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T16:35:38.125+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:35:38.125+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T16:35:38.125+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:35:38.140+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.085 seconds
[2024-02-23T16:36:31.280+0530] {processor.py:161} INFO - Started process (PID=15741) to work on /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:36:31.333+0530] {processor.py:830} INFO - Processing file /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-23T16:36:31.336+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:36:31.336+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:36:31.348+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:36:31.346+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-02-23T16:36:31.349+0530] {logging_mixin.py:188} INFO - [2024-02-23T16:36:31.349+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-02-23T16:36:31.349+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-23T16:36:31.379+0530] {processor.py:183} INFO - Processing /home/arun/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.107 seconds
