[2024-02-29T18:19:36.918+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: THE_second_dag.first_task scheduled__2024-02-29T00:04:00+00:00 [queued]>
[2024-02-29T18:19:36.936+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: THE_second_dag.first_task scheduled__2024-02-29T00:04:00+00:00 [queued]>
[2024-02-29T18:19:36.936+0530] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-02-29T18:19:37.005+0530] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): first_task> on 2024-02-29 00:04:00+00:00
[2024-02-29T18:19:37.011+0530] {standard_task_runner.py:60} INFO - Started process 5435 to run task
[2024-02-29T18:19:37.028+0530] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'THE_second_dag', 'first_task', 'scheduled__2024-02-29T00:04:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/.ipynb_checkpoints/first-dag-1-checkpoint.py', '--cfg-path', '/tmp/tmpugkf8_gf']
[2024-02-29T18:19:37.029+0530] {standard_task_runner.py:88} INFO - Job 42: Subtask first_task
[2024-02-29T18:19:37.122+0530] {task_command.py:423} INFO - Running <TaskInstance: THE_second_dag.first_task scheduled__2024-02-29T00:04:00+00:00 [running]> on host arun-VM
[2024-02-29T18:19:37.353+0530] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='THE_second_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-29T00:04:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-29T00:04:00+00:00'
[2024-02-29T18:19:37.361+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-02-29T18:19:37.364+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello world, this is the first task!']
[2024-02-29T18:19:37.382+0530] {subprocess.py:86} INFO - Output:
[2024-02-29T18:19:37.386+0530] {subprocess.py:93} INFO - hello world, this is the first task!
[2024-02-29T18:19:37.386+0530] {subprocess.py:97} INFO - Command exited with return code 0
[2024-02-29T18:19:37.428+0530] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=THE_second_dag, task_id=first_task, execution_date=20240229T000400, start_date=20240229T124936, end_date=20240229T124937
[2024-02-29T18:19:37.478+0530] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-29T18:19:37.496+0530] {taskinstance.py:3280} INFO - 2 downstream tasks scheduled from follow-on schedule check
