[2024-02-29T18:14:01.335+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: THE_second_dag.second_task scheduled__2024-02-26T00:00:00+00:00 [queued]>
[2024-02-29T18:14:01.344+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: THE_second_dag.second_task scheduled__2024-02-26T00:00:00+00:00 [queued]>
[2024-02-29T18:14:01.345+0530] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-02-29T18:14:01.477+0530] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): second_task> on 2024-02-26 00:00:00+00:00
[2024-02-29T18:14:01.501+0530] {standard_task_runner.py:60} INFO - Started process 5127 to run task
[2024-02-29T18:14:01.538+0530] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'THE_second_dag', 'second_task', 'scheduled__2024-02-26T00:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/.ipynb_checkpoints/first-dag-1-checkpoint.py', '--cfg-path', '/tmp/tmpypy37pw8']
[2024-02-29T18:14:01.541+0530] {standard_task_runner.py:88} INFO - Job 31: Subtask second_task
[2024-02-29T18:14:01.982+0530] {task_command.py:423} INFO - Running <TaskInstance: THE_second_dag.second_task scheduled__2024-02-26T00:00:00+00:00 [running]> on host arun-VM
[2024-02-29T18:14:02.622+0530] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='THE_second_dag' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-26T00:00:00+00:00'
[2024-02-29T18:14:02.632+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-02-29T18:14:02.634+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, I am task2 and will be running after task1!']
[2024-02-29T18:14:02.648+0530] {subprocess.py:86} INFO - Output:
[2024-02-29T18:14:02.652+0530] {subprocess.py:93} INFO - hey, I am task2 and will be running after task1!
[2024-02-29T18:14:02.653+0530] {subprocess.py:97} INFO - Command exited with return code 0
[2024-02-29T18:14:03.152+0530] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=THE_second_dag, task_id=second_task, execution_date=20240226T000000, start_date=20240229T124401, end_date=20240229T124403
[2024-02-29T18:14:03.258+0530] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-29T18:14:03.280+0530] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
