[2024-02-29T18:14:43.715+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: THE_second_dag.thrid_task scheduled__2024-02-27T00:00:00+00:00 [queued]>
[2024-02-29T18:14:43.728+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: THE_second_dag.thrid_task scheduled__2024-02-27T00:00:00+00:00 [queued]>
[2024-02-29T18:14:43.729+0530] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-02-29T18:14:43.811+0530] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): thrid_task> on 2024-02-27 00:00:00+00:00
[2024-02-29T18:14:43.815+0530] {standard_task_runner.py:60} INFO - Started process 5151 to run task
[2024-02-29T18:14:43.823+0530] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'THE_second_dag', 'thrid_task', 'scheduled__2024-02-27T00:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/.ipynb_checkpoints/first-dag-1-checkpoint.py', '--cfg-path', '/tmp/tmp8y44lpx1']
[2024-02-29T18:14:43.823+0530] {standard_task_runner.py:88} INFO - Job 35: Subtask thrid_task
[2024-02-29T18:14:44.233+0530] {task_command.py:423} INFO - Running <TaskInstance: THE_second_dag.thrid_task scheduled__2024-02-27T00:00:00+00:00 [running]> on host arun-VM
[2024-02-29T18:14:44.542+0530] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='THE_second_dag' AIRFLOW_CTX_TASK_ID='thrid_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-27T00:00:00+00:00'
[2024-02-29T18:14:44.554+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-02-29T18:14:44.558+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, I am task3 and will be running after task1 at the same time as task2!']
[2024-02-29T18:14:44.581+0530] {subprocess.py:86} INFO - Output:
[2024-02-29T18:14:44.585+0530] {subprocess.py:93} INFO - hey, I am task3 and will be running after task1 at the same time as task2!
[2024-02-29T18:14:44.586+0530] {subprocess.py:97} INFO - Command exited with return code 0
[2024-02-29T18:14:44.733+0530] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=THE_second_dag, task_id=thrid_task, execution_date=20240227T000000, start_date=20240229T124443, end_date=20240229T124444
[2024-02-29T18:14:44.875+0530] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-29T18:14:44.897+0530] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
